### ISSUE TITLE
Using climate.set_temperature to set temp and mode doesn't work

### ISSUE THREAD

**Issue by jak119** [cdpuk/ha-bestway#13]
If I use `climate.set_temperature` when the climate entity is off will only set the temp but not do anything with the `hvac_mode`. The behavior I'd expect from this call is to set the temp to 100º and set the entity to heat. This is how other integrations (e.g., Ecobee) work. 

## Example service call

```yaml
service: climate.set_temperature
data:
  temperature: 100
  hvac_mode: heat
target:
  entity_id: climate.spa_thermostat
```
